services:
  # Backend Node.js service
  - type: web
    name: operational-backend
    runtime: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://root:${MYSQL_ROOT_PASSWORD}@operational-mysql:3306/operational
      - key: CLICKHOUSE_URL
        value: "" # Optional: Set if using ClickHouse
      - key: API_URL
        value: https://api.operational.co
      - key: APP_URL
        value: https://app.operational.co
      - key: VAPID_EMAIL
        value: ""
      - key: VAPID_PUBLIC_KEY
        value: ""
      - key: VAPID_PRIVATE_KEY
        value: ""
      - key: RESEND
        value: ""
      - key: OPERATIONAL
        value: ""
      - key: PORT
        value: 8080
      - key: SECRET
        generateValue: true
      - key: EVENT_STORE
        value: mysql
      - key: STRIPE_TEST_KEY
        value: "p"
      - key: STRIPE_TEST_SECRET
        value: ""
      - key: STRIPE_LIVE_KEY
        value: ""
      - key: STRIPE_LIVE_SECRET
        value: ""

  # MySQL Service
  - type: pserv
    name: operational-mysql
    image: 
      type: registry-image
      name: mysql
      tag: 8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: operational
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10

  # Frontend static SPA
  - type: web
    name: operational-frontend
    runtime: static
    rootDir: app
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

envVarGroups:
  - name: operational-settings
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
